import './about.css';
import './advanced.css';
import './basic.css';
import './detail.css';
import './dic.css';
import './global.css';
import './header.css';
import './landing.css';
import './single.css';
import './word.css'